import type { LegalDocument } from "./contracts";

const clauses = [
  { id: "1", heading: "The agreement", page: 1, original: "This Services Agreement is entered into on 1 September 2026 between Northstar Studio Ltd. (the Client) and Alex Morgan (the Consultant). The Consultant shall provide brand strategy and visual identity design services as set out in Schedule A. The initial term shall expire on 30 November 2026.", plain: "You are agreeing to create a brand strategy and visual identity for Northstar Studio. The agreement starts on 1 September 2026 and the first term ends on 30 November 2026. The specific work is described in Schedule A." },
  { id: "2", heading: "Payment terms", page: 1, original: "The Client shall pay a total fee of GBP 6,000, with 50% payable upon execution and the remaining 50% within thirty (30) days of final delivery. The Client may withhold disputed amounts pending resolution. No late payment interest is specified under this Agreement.", plain: "The total fee is GBP 6,000. Half is due when the agreement is signed, and the other half is due within 30 days of your final delivery. The client can hold back disputed payments. The agreement does not set an interest rate for late payment." },
  { id: "3", heading: "Ownership of your work", page: 2, original: "All intellectual property rights in the Deliverables, including preliminary concepts and working files, shall vest exclusively in the Client upon creation, irrespective of payment. The Consultant shall not display the Deliverables in any portfolio without the Client's prior written consent.", plain: "The client owns the finished work, early concepts, and working files as soon as you create them, even before you are paid. You need the client's written permission to show any of this work in your portfolio." },
  { id: "4", heading: "Ending the agreement", page: 2, original: "Either party may terminate this Agreement upon thirty (30) days' written notice. On termination, the Consultant shall be entitled to payment for completed and accepted Deliverables only. No compensation shall be due for work in progress or reserved capacity.", plain: "Either side can end the agreement by giving 30 days' written notice. You will only be paid for work that is both completed and accepted. The agreement does not provide payment for unfinished work or time you reserved." },
  { id: "5", heading: "Liability and indemnity", page: 3, original: "The Consultant shall indemnify and hold harmless the Client against all claims, damages, costs and expenses arising out of or in connection with the Services, including indirect and consequential losses. The Consultant's aggregate liability under this Agreement shall not be subject to any financial cap.", plain: "You agree to cover the client's claims, damages, costs, and expenses connected with your services, including indirect losses. The agreement places no financial limit on your total liability. A lawyer can explain how this wording may apply to your situation." },
  { id: "6", heading: "Confidentiality", page: 3, original: "Each party shall keep confidential all non-public information disclosed by the other party and shall use such information solely for the performance of this Agreement. This obligation shall survive termination for a period of two (2) years.", plain: "Both sides must keep each other's non-public information private and use it only to carry out the agreement. This duty continues for two years after the agreement ends." },
  { id: "7", heading: "Renewal and governing law", page: 4, original: "This Agreement shall automatically renew for successive three-month terms unless either party gives written notice of non-renewal at least thirty (30) days before the end of the current term. This Agreement shall be governed by the laws of England and Wales. Any amendment must be in writing and signed by both parties.", plain: "The agreement renews automatically for another three months unless either side gives written notice at least 30 days before the current term ends. It says the laws of England and Wales apply. Changes need to be written down and signed by both sides." },
];

export const SAMPLE_DOCUMENT: LegalDocument = {
  id: "sample-service-agreement", filename: "Northstar_Service_Agreement.pdf", uploadedAt: "2026-09-01T09:00:00.000Z", pageCount: 4,
  text: clauses.map(c => `${c.id}. ${c.heading}\n${c.original}`).join("\n\n"),
  sample: true, messages: [], checked: [],
  analysis: {
    title: "Service agreement", documentType: "Freelance services", clauses,
    summary: "A three-month design agreement between you and Northstar Studio for GBP 6,000. It covers your scope of work, payment, and ownership. A few terms deserve a closer look before you sign.",
    findings: [
      { id: "r1", category: "risk", title: "Your liability has no limit", description: "You could be responsible for losses beyond the value of this project. There is no financial cap on your liability.", severity: "high", clauseId: "5", quote: "The Consultant's aggregate liability under this Agreement shall not be subject to any financial cap.", date: null },
      { id: "r2", category: "risk", title: "Ownership transfers before payment", description: "The client owns your work as soon as it is created, including drafts, even if you have not been paid.", severity: "high", clauseId: "3", quote: "shall vest exclusively in the Client upon creation, irrespective of payment", date: null },
      { id: "r3", category: "risk", title: "Unfinished work may go unpaid", description: "If the agreement ends early, only completed and accepted work is payable. Work in progress is excluded.", severity: "medium", clauseId: "4", quote: "No compensation shall be due for work in progress or reserved capacity.", date: null },
      { id: "o1", category: "obligation", title: "Get permission for your portfolio", description: "Obtain written consent from the client before displaying any deliverables in your portfolio.", severity: "medium", clauseId: "3", quote: "shall not display the Deliverables in any portfolio without the Client's prior written consent", date: null },
      { id: "o2", category: "obligation", title: "Keep shared information confidential", description: "Both parties' confidentiality obligations continue for two years after termination.", severity: "low", clauseId: "6", quote: "This obligation shall survive termination for a period of two (2) years.", date: null },
      { id: "d1", category: "date", title: "Initial term ends", description: "The initial term expires on 30 November 2026. Renewal requires attention before this date.", severity: "medium", clauseId: "1", quote: "The initial term shall expire on 30 November 2026.", date: "2026-11-30" },
      { id: "d2", category: "date", title: "30-day non-renewal notice", description: "Written notice must be given at least 30 days before the current term ends. Ask a lawyer to confirm delivery and deadline rules.", severity: "medium", clauseId: "7", quote: "at least thirty (30) days before the end of the current term", date: null },
    ],
    questions: ["Could my liability be limited, and what losses does the indemnity cover?", "Can ownership transfer only after full payment, with an exception for my pre-existing materials?", "How could payment for work in progress be addressed if the agreement ends early?", "What notice delivery method and deadline apply if I do not want to renew?"],
  },
};

export function answerSample(question: string): { content: string; citations: string[] } {
  const q = question.toLowerCase();
  if (/pay|paid|fee|money|invoice|late/.test(q)) return { content: "In this sample, the fee is GBP 6,000: GBP 3,000 when signed and GBP 3,000 within 30 days of final delivery. The client may withhold disputed amounts. Clause 2 specifies no late payment interest. Clause 4 only provides payment for completed and accepted work if the agreement ends early. A lawyer can explain what these terms mean for your circumstances.", citations: ["2", "4"] };
  if (/end|terminat|cancel|notice|renew/.test(q)) return { content: "Clause 4 allows either party to end this sample agreement with 30 days' written notice. Only completed and accepted deliverables are payable. Clause 7 separately requires at least 30 days' written notice to prevent automatic renewal for another three months. The document does not specify a notice delivery method.", citations: ["4", "7"] };
  if (/own|portfolio|copyright|intellectual/.test(q)) return { content: "Clause 3 says the client owns all deliverables, preliminary concepts, and working files upon creation, even before payment. It also requires written consent to display work in your portfolio. You could ask a legal professional about payment-linked transfer and permission to show your work.", citations: ["3"] };
  if (/risk|liabil|indemn|concern/.test(q)) return { content: "Three terms in this sample deserve discussion with a legal professional: clause 5 has no financial cap on your liability and includes indirect losses; clause 3 transfers ownership before payment; and clause 4 excludes payment for work in progress after termination. These are points to clarify, not a determination that the agreement is unlawful or unsuitable.", citations: ["5", "3", "4"] };
  if (/confiden|private|secret/.test(q)) return { content: "Clause 6 requires both parties to keep non-public information confidential and use it only to perform the agreement. This continues for two years after termination.", citations: ["6"] };
  if (/summar|overview|about|scope/.test(q)) return { content: SAMPLE_DOCUMENT.analysis.summary, citations: ["1", "2"] };
  return { content: "This sample preview has prepared answers about payment, termination, ownership, confidentiality, and liability. I cannot establish the answer to that question from this preview. Live document questions require the AI connection. A qualified legal professional can help with advice about your circumstances.", citations: [] };
}
